# Generated by Django 3.1.1 on 2020-10-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200929_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title_status',
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titleimage', to='shop.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titleprod', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='title_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titlei', to='shop.titleimage'),
        ),
    ]
