# Generated by Django 3.1.1 on 2020-10-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201006_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_image',
        ),
        migrations.DeleteModel(
            name='TitleImage',
        ),
    ]
