"""
Django settings for eCom project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from sys import platform
# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7ek)&nxtv=sdf-h14kpb4v&th43k3erzo5pl)d6x9aoah+g*pq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CART_SESSION_ID = 'cart'
# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userprofile',
    'cart',
    'orders',
    'shop',
    'account',
    #'account.apps.AccountConfig',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eCom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart'
            ],
        },
    },
]



WSGI_APPLICATION = 'eCom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if platform == "win32":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'shop',
            'USER': 'postgres',
            'PASSWORD': '31467539',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        },
    }
    CELERY_BROKER_URL = 'amqp://foit:foit@localhost:5672//'
    #CELERY_BROKER_URL = 'redis://:p2a9dc382d99731d4c907e92eccbd6f4477fc1ec174c5a8bebe3ad8d782e96583@ec2-18-208-66-227.compute-1.amazonaws.com:15849'
    #CELERY_BROKER_URL = 'amqp://admin:31467539@3.14.88.200:5672//'
    #CELERY_BROKER_URL = 'amqp://admin:31467539@3.14.88.200:5672//'
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'ddhvm6vis6l50q',
            'USER': 'rcvnqprojakzcw',
            'PASSWORD': 'b955e084aa866d901c3c5b29a3145bff178f99554f1bed718b9ed4fdb86b51f6',
            'HOST': 'ec2-3-226-231-4.compute-1.amazonaws.com',
            'PORT': '5432',
            },
    }
    #CELERY_BROKER_URL = 'amqp://admin:31467539@3.14.88.200:5672//'
    CELERY_BROKER_URL = 'redis://:p2a9dc382d99731d4c907e92eccbd6f4477fc1ec174c5a8bebe3ad8d782e96583@ec2-18-208-66-227.compute-1.amazonaws.com:15849'
    here = lambda *x: os.path.join(os.path.abspath(os.path.dirname(__file__)), *x)
    PROJECT_ROOT = here("..")
    root = lambda *x: os.path.join(os.path.abspath(PROJECT_ROOT), *x)
    PROJECT_DIR = os.path.dirname(__file__)
    TEMPLATE_DIRS = (
        os.path.join(PROJECT_DIR, 'templates'),
        root('templates'),
    )

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'shop.my_auth.UserEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

PROJECT_ROOT = os.path.dirname(__file__)

#STATIC_ROOT = os.path.join(PROJECT_ROOT, 'stasic')

STATIC_URL = '/static/'

#STATICFILES_DIRS = (os.path.join('static'),)
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'static_root')
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static', 'static_files'),)
MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR,  'static')

PROJECT_ROOT = os.path.dirname(__file__)

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'stasic')

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join('static'),)

SESSION_SAVE_EVERY_REQUEST = True

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_HOST_USER = 'example_mail_django@bk.ru'
EMAIL_HOST_PASSWORD = '?Zk|Lb8PQce659tz'
EMAIL_PORT = 2525

#CELERY_BROKER_URL = 'amqp://localhost'
#CELERY_BROKER_URL = 'amqp://foit:foit@localhost:5672//'
BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = 'django-db'
# celery setting.
CELERY_CACHE_BACKEND = 'default'

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

